package test.java.pk1a;

import main.java.pk1.ClassForMath;
import junit.framework.*;
//fff\rttttttttttttttttt
////yyyyy
//tg



public class TestClassForMath5a extends TestCase {

        public void testMultXxxx5()  throws InterruptedException {
            ClassForMath tester = new ClassForMath();
            System.out.println("1");
            System.out.print("2");
            System.out.print("hello");
            System.err.print("hello again");
		 Thread.sleep(10000);
               Assert.assertEquals("Result", 31, tester.multiply(6, 5));

        }
        public void testMultXxx5()  throws InterruptedException {
            ClassForMath tester = new ClassForMath();
            System.out.print("2");
            System.out.print("hello");
            System.err.print("hello again");
		 Thread.sleep(10000);
               Assert.assertEquals("Result", 31, tester.multiply2(6, 5));
       }
////t

public void testSummaXxxx5() throws InterruptedException {
	
    ClassForMath tester = new ClassForMath();
    System.out.println("3");
	 Thread.sleep(10000);
    
       Assert.assertEquals("Result", 17, tester.summa(12, 5));
//dddddd
}
public void testDifferenceXxx5() throws InterruptedException {
    ClassForMath tester = new ClassForMath();
    System.out.println("4");
	 Thread.sleep(10000);
       Assert.assertEquals("Result", 8, tester.difference(12, 5));

}
public void testDifferenceXxx5a() throws InterruptedException {
//sdfsfdfsdfdfsdf
    ClassForMath tester = new ClassForMath();
	 Thread.sleep(10000);
       Assert.assertEquals("Result", 6, tester.difference(12, 5));

}
public void testDifference5Xxx5a() throws InterruptedException {
    ClassForMath tester = new ClassForMath();
	 Thread.sleep(10000);
       Assert.assertEquals("Result", 7, tester.difference(12, 5));

}
public void testDivisionXxx5() throws InterruptedException {
    ClassForMath tester = new ClassForMath();
	 Thread.sleep(10000);
       Assert.assertEquals("Result", 7, tester.division(8,1));}

public void testDoubleSummaXxx5() throws InterruptedException {
	//dfdfdfsfsdfsfdsfsf
	//dfsfdfsdfdfsdfsff
    ClassForMath tester = new ClassForMath();
	 Thread.sleep(10000);
       Assert.assertEquals("Result", 34, tester.double_summa(12, 5));
       //zzxzxzxzxzxzxzxzxzxzx
       
}
public void testTripleSummaXxx5() throws InterruptedException
{ClassForMath test1= new ClassForMath();
  Thread.sleep(10000);
Assert.assertEquals("Result", 12, test1.triple_summa(2,2) );
	}


}
